// <auto-generated />
using System.Collections.Generic;
using HotelAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250825065934_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelAPI.Models.HotelSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountsPersonContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountsPersonEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountsPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConciergeContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConciergeEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConciergeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("FacilitiesAvailable")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("HotelContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceptionPersonContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceptionPersonEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReceptionPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReservationPersonContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReservationPersonEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReservationPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalesPersonContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalesPersonEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalesPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialRemarks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HotelSales");
                });
#pragma warning restore 612, 618
        }
    }
}
